openapi: 3.0.0
info:
  title: Vitals API
  description: API documentation for OS infos API
  version: 1.0.0

paths:
  /vitals:
    get:
      summary: Get Vitals
      description: Retrieve a list of vitals.
      tags:
        - Vitals
      responses:
        '200':
          description: A JSON array of vitals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vital'
  /vitals/{id}:
    parameters:
      - name: id
        description: Id of vitals (see docs)
        in: path

    get:
      summary: Get One Vitals
      description: Retrieve one vitals with given id.
      tags:
        - Vitals
      responses:
        '200':
          description: A JSON Vitals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vital'

        '404':
          description: Vitals with given ID doesn't exist.

components:
  schemas:
    Vital:
      type: object
      properties:
        id:
          type: integer
          example: 1
        type:
          type: string
          example: heart-rate
        value:
          type: integer
          example: 72
        unit:
          type: string
          example: bpm