openapi: 3.0.0
info:
  title: Vitals API
  description: API documentation for OS infos API
  version: 1.0.0

paths:
  /vitals:
    get:
      summary: Get Vitals
      description: Retrieve a list of vitals.
      tags:
        - Vitals
      responses:
        '200':
          description: A JSON array of vitals
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Vital'
  /vitals/{id}:
    parameters:
      - name: id
        description: Id of vitals (see docs)
        in: path

    get:
      summary: Get One Vitals
      description: Retrieve one vitals with given id.
      tags:
        - Vitals
      responses:
        '200':
          description: A JSON Vitals
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Vital'

        '404':
          description: Vitals with given ID doesn't exist.

  /network/interface/{name}:
    parameters:
      - name: name
        description: Name of interface
        in: path

    get:
      summary: Get one interface
      description: Retrieve on interface with given name.
      tags:
        - Network
      responses:
        '200':
          description: A JSON Interface infos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Interface'

        '404':
          description: Interface with given name doesn't exist.
  

components:
  schemas:
    Vital:
      type: object
      properties:
        id:
          type: integer
          example: 1
        type:
          type: string
          example: heart-rate
        value:
          type: integer
          example: 72
        unit:
          type: string
          example: bpm
    Interface:
      type: object
      properties:
        name:
          type: string
          example: eth0
        ip:
          type: string
          example: 10.1.1.30
        mac:
          type: string
          example: 'aa:bb:cc:dd:ee:ff'
        mask:
          type: string
          example: 255.255.255.0